MovieApp.WebUI/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieApp.WebUI.Models;

namespace MovieApp.WebUI.Controllers
{
    public class MovieController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List()
        {
            return View(MovieRepository.Movies);
        }
    }
}

MovieApp.WebUI/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}


<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Album example for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/css/album.css" rel="stylesheet" />
</head>

<body>
    @Html.Partial("_header")
    <main role="main">
        @RenderBody()
    </main>

@Html.Partial("_footer")

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="~/js/jquery-slim.min.js"><\/script>')</script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/holder.min.js"></script>
</body>
</html>

MovieApp.WebUI/Views/Shared/_MovieList.cshtml
@model IEnumerable<Movie>

@foreach (var item in Model)
{
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top" src="~/img/@item.Image" alt="@item.Name">
            <div class="card-body">
                <p class="card-text">@item.Name</p>
            </div>
            <div class="card-footer text-muted">
                <a asp-controller="Home" asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Details</a>
                2 days ago
            </div>
        </div>
    </div>
}

MovieApp.WebUI/Views/Shared/_footer.cshtml
<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting started guide</a>.</p>
    </div>
</footer>

MovieApp.WebUI/Views/Shared/_header.cshtml
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-action="Index" asp-controller="Home">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="List" asp-controller="Movie">Movies</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
        </div>
    </nav>
</header>