MovieApp.WebUI/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.WebUI.Models
{
    public class Movie : IDisposable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }

        public void Dispose()
        {
            GC.SuppressFinalize(this);
        }
    }
}

MovieApp.WebUI/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieApp.WebUI.Models;

namespace MovieApp.WebUI.Controllers
{
    public class MovieController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List()
        {
            return View(MovieRepository.Movies);
        }
    }
}

MovieApp.WebUI/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.WebUI.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View(CategoryRepository.Categories);
        }
    }
}

MovieApp.WebUI/Views/Movie/List.cshtml
@model IEnumerable<Movie>
@{
    ViewData["Title"] = "Movies List";
}


<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                @await Component.InvokeAsync("Menu")
            </div>
            <div class="col-md-8">
                <div class="row">
                    @Html.Partial("_MovieList", Model)
                 </div>
                </div>
            </div>
        </div>
    </div>